name: password_manager
description: A simple yet secure password manager built in Dart, featuring master password authentication and encrypted password storage.
version: 1.0.0
repository: https://github.com/alessiocascini/password-manager.git

environment:
  sdk: ^3.7.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  encrypt: ^5.0.3
  crypto: ^3.0.6
  pointycastle: ^3.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
