name: Analyze

on:
  push:
    branches: [main, chore/serverpod]
  pull_request:
    branches: [main, chore/serverpod]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.8.0

      - name: Add serverpod_cli as dev dependency
        working-directory: password_manager_server
        run: dart pub add --dev serverpod_cli

      - name: Install dependencies
        working-directory: password_manager_server
        run: dart pub get

      - name: Generate serverpod code
        working-directory: password_manager_server
        run: dart run serverpod_cli generate

      - name: Analyze
        working-directory: password_manager_server
        run: dart analyze --fatal-infos
