name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VERSION: '3.0.0'
      SERVERPOD_PASSWORD_database: '3Cswj5_ZYO8FS8fjMSL4lEP2Wnwye-HX'
      SERVERPOD_PASSWORD_redis: 'wOw_0UnyU6_cIY0pdkIoslVQw2T1cuXW'

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      - name: Start containers
        working-directory: password_manager_server
        run: docker compose up --build -d

      - name: Install dependencies
        working-directory: password_manager_server
        run: dart pub get

      - name: Install Serverpod CLI
        working-directory: password_manager_server
        run: dart pub global activate serverpod_cli $VERSION

      - name: Run Serverpod generator
        working-directory: password_manager_server
        run: serverpod generate

      - name: Run tests
        working-directory: password_manager_server
        run: dart test

      - name: Stop containers
        if: always()
        working-directory: password_manager_server
        run: docker compose down -v
